server {
    listen 80 default_server;
    server_name __IP__;
    server_tokens off;
    location /.well-known/acme-challenge/ { root /var/www/acme; }
    location / { return 308 https://__IP__$request_uri; }
}
